# Generated by Django 4.0.4 on 2022-07-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecoverTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=10, null=True)),
                ('ids', models.IntegerField()),
            ],
        ),
    ]
