# Generated by Django 4.0.4 on 2022-07-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_cart_stock_delete_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Price',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Quantity',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cart',
            name='TPrice',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Price',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Product',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Quantity',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userrecovertable',
            name='ids',
            field=models.CharField(max_length=1000),
        ),
    ]
