# Generated by Django 4.0.4 on 2022-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0004_alter_cart_price_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userrecovertable',
            name='ids',
            field=models.IntegerField(),
        ),
    ]
