# Generated by Django 4.0.4 on 2022-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0005_alter_cart_price_alter_stock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
