# Generated by Django 4.0.4 on 2022-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0007_alter_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Product',
            field=models.CharField(max_length=1000),
        ),
    ]
