# Generated by Django 4.0.4 on 2022-08-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0010_reciept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciept',
            name='Generated_By',
        ),
    ]
