# Generated by Django 4.0.4 on 2022-08-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0011_remove_reciept_generated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=1000, unique=True)),
                ('Price', models.IntegerField()),
                ('Quantity', models.CharField(max_length=1000)),
                ('TPrice', models.CharField(max_length=1000)),
                ('Generated_By', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Reciept',
        ),
    ]
