# Generated by Django 4.0.4 on 2022-08-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0012_customerreciept_delete_reciept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreciept',
            name='Product',
            field=models.CharField(max_length=1000),
        ),
    ]
