# Generated by Django 4.0.4 on 2022-08-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0014_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
